global:
  scrape_interval: 15s  # Collect metrics every 15 seconds
  evaluation_interval: 30s  # Evaluate alerts every 30 seconds

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9090']  # Replace with your app URL

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alert_rules.yml"
