app:
  name: Fintech App
  version: 1.0.0
  environment: production
  port: 5000

database:
  host: localhost
  port: 5432
  user: fintech_admin
  password: secret_password
  name: fintech_db

logging:
  level: INFO
  file: logs/app.log

observability:
  metrics_enabled: true
  prometheus_port: 9090
